### ISSUE TITLE
Remove class Simple_Google_Analytics_Tracking

### ISSUE THREAD

**Issue by salcode** [dustyndoyle/simple-google-analytics-tracking#3]
I think you could remove the class __Simple_Google_Analytics_Tracking__ and instead solely have the line
```
foreach ( glob( dirname( __FILE__ ) . '/includes/*.php' ) as $file ) { include $file; }
```

I know others (e.g. @tbcorr) prefer using a class with a singleton pattern like this but I don't see an advantage to using it here.

**Comment by dustyndoyle** [comment]
I am now just using this to include files, instead of the class.
Thanks @salcode
